# https://starwars.fandom.com/wiki/Main_Page
sw <- c(
  "R2-D2", "Rebel Alliance",
  "QUI-GON", "Galactic Republic",
  "NUTE GUNRAY" , "Confederacy of Independent Systems",
  "PK-4", "Trade Federation",
  "TC-14", "Trade Federation",
  "OBI-WAN", "Rebel Alliance",
  "DOFINE", "Confederacy of Independent Systems",
  "RUNE", "Jedi Order",
  "TEY HOW", "Trade Federation",
  "EMPEROR", "Sith Order",
  "CAPTAIN PANAKA", "Galactic Empire",
  "SIO BIBBLE", "Galactic Republic",
  "JAR JAR", "Galactic Empire",
  "TARPALS", "Gungan",
  "BOSS NASS" , "Gungan",
  "PADME", "Galactic Empire",
  "RIC OLIE", "NA",
  "WATTO" , "NA",
  "ANAKIN", "Galactic Republic",
  "SEBULBA", "NA",
  "JIRA", "NA",
  "SHMI", "NA",
  "C-3PO", "Galactic Empire",
  "DARTH MAUL", "Sith Order",
  "KITSTER", "NA",
  "WALD", "NA",
  "FODE/BEED", "NA",
  "JABBA", "NA",
  "GREEDO", "NA",
  "VALORUM", "Galactic Republic",
  "MACE WINDU", "Galactic Republic",
  "KI-ADI-MUNDI", "Galactic Republic",
  "YODA", "Galactic Republic",
  "RABE", "Galactic Republic",
  "BAIL ORGANA", "Galactic Empire",
  "GENERAL CEEL", "Gungan",
  "BRAVO TWO" , "Galactic Republic",
  "BRAVO THREE", "Galactic Republic",
  "CAPTAIN TYPHO", "Galactic Republic",
  "SENATOR ASK AAK", "Galactic Republic",
  "ORN FREE TAA", "Galactic Empire",
  "SOLA", "Galactic Republic",
  "JOBAL", "NA",
  "RUWEE", "NA",
  "TAUN WE", "Galactic Empire",
  "LAMA SU", "Galactic Empire",
  "BOBA FETT", "Galactic Empire",
  "JANGO FETT", "Confederacy of Independent Systems",
  "OWEN", "NA",
  "BERU", "NA",
  "CLIEGG", "NA",
  "COUNT DOOKU", "Confederacy of Independent Systems",
  "SUN RIT", "Confederacy of Independent Systems",
  "POGGLE", "Confederacy of Independent Systems",
  "PLO KOON", "Galactic Republic",
  "ODD BALL", "Galactic Empire",
  "GENERAL GRIEVOUS", "Confederacy of Independent Systems",
  "FANG ZAR", "Galactic Empire",
  "MON MOTHMA", "Galactic Empire",
  "GIDDEAN DANU", "Galactic Republic",
  "CLONE COMMANDER GREE", "Galactic Republic",
  "CLONE COMMANDER CODY", "Galactic Empire",
  "TION MEDON", "Galactic Republic",
  "CAPTAIN ANTILLES", "Galactic Republic",
  "DARTH VADER", "Sith Order",
  "CHEWBACCA", "Galactic Republic",
  "LUKE", "Jedi Order",
  "CAMIE", "NA",
  "BIGGS", "Rebel Alliance",
  "LEIA", "Rebel Alliance",
  "MOTTI", "Galactic Empire",
  "TARKIN", "Galactic Empire",
  "HAN", "Rebel Alliance",
  "DODONNA", "Rebel Alliance",
  "GOLD LEADER", "Rebel Alliance",
  "WEDGE", "Rebel Alliance",
  "RED LEADER", "Rebel Alliance",
  "RED TEN", "Rebel Alliance",
  "RIEEKAN", "Rebel Alliance",
  "DERLIN", "Rebel Alliance",
  "ZEV", "Rebel Alliance",
  "PIETT", "Galactic Empire",
  "OZZEL", "Galactic Empire",
  "DACK", "NA",
  "JANSON", "Rebel Alliance",
  "NEEDA", "Galactic Empire",
  "LANDO", "Rebel Alliance",
  "JERJERROD", "Galactic Empire",
  "BIB FORTUNA", "NA",
  "BOUSHH", "NA",
  "ADMIRAL ACKBAR", "Rebel Alliance"
)
sw <- data.frame(name = sw[c(T, F)]
                 , affiliation = sw[c(F, T)])
sw$remove <- ifelse(!(sw$affiliation %in% c("Confederacy of Independent Systems"
                                            , "Galactic Empire"
                                            , "Galactic Republic"
                                            , "Jedi Order"
                                            , "Rebel Alliance"
                                            , "Sith Order")), 0, 1)
sw$label <- as.numeric(factor(sw$affiliation)) * sw$remove